/**
 * @file main.c
 * @brief {{PROJECT_DISPLAY_NAME}} - Blinky Example
 * @author Generated by zephyr-meta
 */

#include <zephyr/kernel.h>
#include <zephyr/drivers/gpio.h>
#include <zephyr/logging/log.h>

LOG_MODULE_REGISTER(main, LOG_LEVEL_INF);

/* LED0 device tree alias */
#define LED0_NODE DT_ALIAS(led0)
static const struct gpio_dt_spec led = GPIO_DT_SPEC_GET(LED0_NODE, gpios);

int main(void)
{
	LOG_INF("Starting {{PROJECT_DISPLAY_NAME}}...");
	LOG_INF("Board: {{BOARD_NAME}}");

	/* Check if LED device is ready */
	if (!gpio_is_ready_dt(&led)) {
		LOG_ERR("LED device not ready");
		return -1;
	}

	/* Configure LED pin as output */
	int ret = gpio_pin_configure_dt(&led, GPIO_OUTPUT_ACTIVE);
	if (ret < 0) {
		LOG_ERR("Failed to configure LED pin: %d", ret);
		return ret;
	}

	LOG_INF("LED initialized successfully");

	/* Main loop: Blink LED */
	while (1) {
		gpio_pin_toggle_dt(&led);
		k_msleep(1000);
	}

	return 0;
}
